/*Copyright (c) 2017-2018 devuser1.com All Rights Reserved.
 This software is the confidential and proprietary information of devuser1.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with devuser1.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class UserDetailsResponse implements Serializable {

    private String username;
    private String password;

    @ColumnAlias("USERNAME")
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @ColumnAlias("PASSWORD")
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserDetailsResponse)) return false;
        final UserDetailsResponse userDetailsResponse = (UserDetailsResponse) o;
        return Objects.equals(getUsername(), userDetailsResponse.getUsername()) &&
                Objects.equals(getPassword(), userDetailsResponse.getPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUsername(),
                getPassword());
    }
}
